ci: update homebrew tap on release
airbytehq/abctl pull request #90
Opened 2024-08-26 20:02 UTC by abuchanan-airbyte

https://github.com/airbytehq/airbyte-internal-issues/issues/9450

This adds steps to the release workflow to checkout the homebrew tap, update the version, and push a commit to that repo.

This depends on having write access to the homebrew tap repo, which is granted via [Deploy Keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys)

I made up a robot user for the git name/email here. I'm not sure if we have an actual user/account that would be better.

2024-08-27 03:17 UTC, bgroff approved these changes

2024-08-27 17:01 UTC, colesnodgrass requested changes

2024-08-27 17:01 UTC, colesnodgrass commented on .github/workflows/release.yml
> +          git commit -a -m "Update abctl to $ABCTL_VERSION"
this needs to be a conventional commit message, i.e. `chore: update abctl to $ABCTL_VERSION`

2024-08-27 17:19 UTC, abuchanan-airbyte commented on .github/workflows/release.yml
> +          repository: abuchanan-airbyte/homebrew-tap
oops, good catch. fixed!

2024-08-27 20:15 UTC, abuchanan-airbyte commented
Updated to https://github.com/airbyte-prodeng and added the email as a secret to this repo

2024-08-29 16:01 UTC, colesnodgrass approved these changes

2024-08-29 17:55 UTC, merged